metabrainz/listenbrainz-android

- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/services/BrainzPlayerService.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/services/notification/BrainzPlayerNotificationManager.kt
Fixed firstStartError which crashed the app on first ever launch.
Fixed notification player of BrainzPlayer. Now when the app is stopped, the notification player disappears. The player reappears when app is launched and play button is hit.
> Fixed firstStartError and fixed notification of brainzplayer

- app/src/main/java/org/listenbrainz/android/App.kt
MOBILE-117: https://tickets.metabrainz.org/browse/MOBILE-117
Even though I was not able to reproduce the bug, this check makes sure the app is in foreground. (Between onCreate and onStop)
> MOBILE-117

- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/album/AlbumScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/artist/ArtistScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/playlist/PlaylistScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/songs/SongScreen.kt
**BrainzPlayer Changes**
- Fixed text colors to be readable in both dark and light themes, as the earlier text was the same as the background color in some parts of the app creating a sense of confusion.
- Changed the background of the playlist screen to be the same as others.
- Changed checkbox colors to look more interactive.  
**Changes can be seen below**
> UI fixes : Fixed colors of some items to be according to theme.

- .github/workflows/attach-release.yml
- Everytime a GitHub release is made, the apk will automatically be attached to it.
> Attach apk to GitHub release

- app/src/main/java/org/listenbrainz/android/model/Playable.kt
- app/src/main/java/org/listenbrainz/android/service/BrainzPlayerService.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/AlbumScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/ArtistScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/PlaylistScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/SongScreen.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
This PR contains the feature to add a song, Playlist, or album to the queue, and also has a feature for playing next. 
Some changes in UI such as making the card as same as the queue card because there are two different types of cards to show the list of songs and a drop-down button so the user can choose to play next or to add to the queue.
@akshaaatt bhaiya can you please review it and suggest any changes if required?
> Feat: All Queue Features are added

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/listenbrainz/android/model/AdditionalInfo.kt
- app/src/main/java/org/listenbrainz/android/model/ListenSubmitBody.kt
- app/src/main/java/org/listenbrainz/android/model/ListenTrackMetadata.kt
- app/src/main/java/org/listenbrainz/android/model/MbidMapping.kt
- app/src/main/java/org/listenbrainz/android/ui/components/ListenCards.kt
- app/src/main/java/org/listenbrainz/android/ui/components/YimNavigationStation.kt
- app/src/main/java/org/listenbrainz/android/ui/components/YimShareButton.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/AllUsersListens.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListensScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim/YearInMusicActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim/YimDiscoverScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim/YimEndgameScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim/YimHomeScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim/YimTopAlbumsScreen.kt
- app/src/main/java/org/listenbrainz/android/util/ListenHandler.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSessionListener.kt
- app/src/main/java/org/listenbrainz/android/util/Utils.kt
- app/src/main/java/org/listenbrainz/android/util/connectivityobserver/NetworkConnectivityViewModel.kt
- app/src/main/java/org/listenbrainz/android/util/connectivityobserver/NetworkConnectivityViewModelImpl.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ListensViewModel.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/YimViewModel.kt
- build.gradle
- sharedTest/src/main/java/org/listenbrainz/sharedtest/mocks/MockNetworkConnectivityViewModel.kt
Fixes MOBILE - [124](https://tickets.metabrainz.org/browse/MOBILE-124), [128](https://tickets.metabrainz.org/browse/MOBILE-128), [131](https://tickets.metabrainz.org/browse/MOBILE-131)
1) [124](https://tickets.metabrainz.org/browse/MOBILE-124) : Listen Service can record local listens as well as listens from other media sources that don't share metadata properly. Previously, listens from services like spotify and youtube could only be recorded; but services that don't share metadata properly, trouble the `ListenService` as artist metadata was always null. To fix this, artist metadata can now be extracted from the notification's text as well. New alternatives for title are also added. Fixed in https://github.com/metabrainz/listenbrainz-android/pull/108/commits/e65c7ec9c189a8416ecc7461ddf46c …
> ListenService and YIM fixed

- app/build.gradle
- app/src/androidTest/java/org/listenbrainz/android/TestAppModule.kt
- app/src/androidTest/java/org/listenbrainz/android/YearInMusicActivityTest.kt
- app/src/androidTest/java/org/listenbrainz/android/di/HiltTestApplication.kt
- app/src/androidTest/java/org/listenbrainz/android/di/TestAppModule.kt
- app/src/main/java/org/listenbrainz/android/repository/AppPreferences.kt
- app/src/main/java/org/listenbrainz/android/repository/AppPreferencesImpl.kt
- app/src/main/java/org/listenbrainz/android/service/ListenService.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/login/LoginActivity.kt
- app/src/main/java/org/listenbrainz/android/util/ListenHandler.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSessionListener.kt
- app/src/main/java/org/listenbrainz/android/util/UserPreferences.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/LoginViewModel.kt
- build.gradle
- sharedTest/build.gradle
- sharedTest/src/main/java/org/listenbrainz/sharedtest/mocks/MockAppPreferences.kt
Listens Service was registering multiple callbacks which led to multiple submissions of the same song and multiple callbacks for same app's music notification. That is fixed now.
ClearSessions method was useless as it had no connection whatsoever with the service components itself, meaning it didn't unregister callbacks as expected.
TestAppModule established to deal with appPreferences easily and thus enabling us to use appPreferences app wide easily now.
Blocking infra added, UI pending.
> Optimised ListenService and adapted appPreferences

- app/src/main/java/org/listenbrainz/android/repository/ListensRepository.kt
- app/src/main/java/org/listenbrainz/android/repository/ListensRepositoryImpl.kt
- app/src/main/java/org/listenbrainz/android/ui/navigation/BottomNavigationBar.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/dashboard/DashboardActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/AllUsersListens.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListensScreen.kt
- app/src/main/java/org/listenbrainz/android/util/ListenHandler.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSessionListener.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ListensViewModel.kt
Listening Service Blacklist UI added. Users can now access the list of apps from which listens have been recorded in the past and enable/disable submitting listens from them. This option can be found on ListensScreen through the floating action button.
In minor tweaks: 
1) Front layer header height was 0.dp, changed it to 56.dp to match height of bottom navigation bar. 
2) Changed minor compose if conditions to animated visibility.
> Blacklist UI added and minor tweaks

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/model/ListenSubmitBody.kt
- app/src/main/java/org/listenbrainz/android/util/ListenHandler.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSessionListener.kt
- app/src/main/java/org/listenbrainz/android/util/cacheService.kt
1) [MOBILE-127](https://tickets.metabrainz.org/browse/MOBILE-127)
2) Listen was only submitted when the previous song was paused, then played and then skipped to desired song. Listens were not submitted at all if songs were played continuously without break.
Redesign with timer to keep seconds in count and removed all the confusing code before.
> Redesigned ListenService

- .github/workflows/android.yml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/listenbrainz/android/ui/screens/dashboard/DashboardActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/AllUsersListens.kt
- app/src/main/java/org/listenbrainz/android/util/NotificationHelper.kt
- app/src/main/java/org/listenbrainz/android/util/Utils.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ListensViewModel.kt
- app/src/main/res/values-h720dp/dimensions.xml
- app/src/main/res/values-night/styles.xml
- app/src/main/res/values/styles.xml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- sharedTest/build.gradle
- YT API to identify listens is working now!
> Youtube API fixes, Bumped dependencies and cleanup

- .github/dependabot.yml
- It was noticed that dependabot informed us about the updates always on a Monday during the weekly meeting. In order to avoid that from happening, we are shifting to a Wednesday.
> Receive Dependabot updates on Wednesdays

- app/src/main/AndroidManifest.xml
- app/src/main/res/values/strings.xml
Clicking the News button in the main screen does not open the News activity as it's not defined in the AndroidManifest
> Fix: Declare NewsBrainzActivity in androidManifest

- app/src/main/java/org/listenbrainz/android/viewmodel/ListensViewModel.kt
- The crash was saying that it was already resumed. This seems to be a bug and we have added a workaround for it.
> Fix Spotify remote crash

- app/src/main/java/org/listenbrainz/android/ui/screens/about/AboutScreen.kt
The About screen links were not clickable, making it less interactive. I fixed this by following [this answer](https://stackoverflow.com/questions/65567412/jetpack-compose-text-hyperlink-some-section-of-the-text).
I have also fixed the Attributions link from
"https://github.com/metabrainz/listenbrainz-android/blob/master/app/src/main/play/asset_attributions.md"
to
"https://github.com/metabrainz/listenbrainz-android/blob/main/asset_attributions.md"
> Fix links not clickable in About screen

- app/src/main/java/org/listenbrainz/android/service/ListenScrobbleService.kt
- The system kills the service after onStartCommand() returns, and it will not re-deliver the last Intent. Instead, the system calls onStartCommand() with a null Intent. We now handle this situation in order to avoid crashes.
> Make intent nullable for service

- app/src/main/java/org/listenbrainz/android/ui/components/SimilarUserCard.kt
- app/src/main/java/org/listenbrainz/android/ui/navigation/TopBar.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/LoginActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim/YearInMusicActivity.kt
- app/src/main/java/org/listenbrainz/android/util/Utils.kt
1) When switching theme, the view models won't get destroyed meaning state will be retained. This also results in quick transition and gives accurate results.
2) YIM was not launching even with user logged in. Fixed that bug (cased by me).
> Fixes: Theme changes now retain state

- app/src/main/java/org/listenbrainz/android/ui/screens/newsbrainz/NewsBrainzScreen.kt
If the title of the blog was very large, it was occupying the full available space and the share button was not visible when I was checking the app today, so changed the code so that title takes only 70% of the row. Also as Aerozol suggested yesterday, added text overflow property to the content of the blog. (https://tickets.metabrainz.org/browse/MOBILE-178?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=70443#comment-70443)
> Rectified a bug, added overflow to text

- app/src/main/java/org/listenbrainz/android/model/yimdata/Yim23AdditionalMetadata.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23DiscoveriesListScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23DiscoveriesScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23MissedSongsScreen.kt
While scrolling to the end in any of the lists present in YIM23, the app suddenly crashes
While creating the models , I mistakenly put caaId as string. So now what happens is when caaId is null for a song, the .toLong() function raises JavaNumberFormatException. To overcome this, I changed the datatype in the model and made some changes where it was used according to the new datatype (Long)
Please test this locally once just to make sure
https://github.com/metabrainz/listenbrainz-android/assets/122373207/93c56eb7-a8ab-41d0-88c7-d8a1f93fdb6c
> MOBILE-182:App Crashes in YIM 23

- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23LandingScreen.kt
In this PR, I changed the code such that the landing screen is never blank as earlier was the case. The users will see a screen initially and depending on status of yim data from view model I am changing the display rendered on the screen. Initially I was comparing yimdata.value.data?.payload?.data to null however that wasn't working because they were being populated with empty values not null.. therefore I used yimdata.value.data?.payload?.data.totalListenCount = 0.. Also removed share button from the screen when YIM is not available as disabling it was not looking good..
> Refactored landing screen so that it is never blank

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/repository/listenservicemanager/ListenServiceManagerImpl.kt
- app/src/main/java/org/listenbrainz/android/repository/remoteplayer/RemotePlaybackHandlerImpl.kt
- fastlane/metadata/android/en-US/changelogs/47.txt
- fastlane/metadata/android/en-US/changelogs/48.txt
1) Concurreny fix in `SpotifyAppRemote` connection functions that caused a crash sometimes. 
Why? Since Spotify sometimes runs callbacks twice, it makes our coroutine resume twice which causes an exception.
2) Typo fix.
Note: Checkout [this](https://github.com/metabrainz/listenbrainz-android/commit/f20f9f8bf93c76d0cfc44e6bdc0ea16735b06952) commit's description where concurrency fix is reverted.
> Concurrency and typo fixes

- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23DiscoveriesListScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23FriendsScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23MissedSongsListScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23NewAlbumsFromTopArtistsScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23TopAlbumsScreen.kt
- app/src/main/java/org/listenbrainz/android/util/Constants.kt
All changes (In accordance with feedback my monkey -> ):
Used 250px for all cover art in YIM to help with loading times
Changed links in music buddies to point to lb instead of beta.lb
> Minor fixes for YIM

- app/src/main/java/org/listenbrainz/android/ui/theme/Theme.kt
Fixes: "UninitializedPropertyAccessException: lateinit property LocalColorScheme has not been initialized" reported on sentry
> Fix uninitialized property

- app/src/main/java/org/listenbrainz/android/model/SocialUiState.kt
- app/src/main/java/org/listenbrainz/android/ui/components/SuccessBar.kt
- app/src/main/java/org/listenbrainz/android/ui/navigation/AppNavigation.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListensScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/main/MainActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/ProfileScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/YearInMusic23Activity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/navigation/Yim23Navigation.kt
- app/src/main/java/org/listenbrainz/android/util/Constants.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/BaseViewModel.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/SocialViewModel.kt
- app/src/main/res/values/strings.xml
https://tickets.metabrainz.org/browse/MOBILE-188?filter=-2
The features in the feed such as writing review , recommend etc were not present in the profile screen even tho the listen cards were there. This made it very bland, hence I refactored so that those features can be done from the profile screen as well!
I used the socialViewModel and called fns for pin and recommend to followers directly. For review and personal recommendation, I had to use feedViewModel as well for filtering out user's followers and had to make a dialog system as was done for the feed. Also , I made sure a toast (snackbar) is displayed every time a successful event is triggered so that the user gets feedback as well. I have added those messages inside constants file as they may be reused. …
> MOBILE-188/Features such as recommend,review in profile screen

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/model/dao/AlbumDao.kt
- app/src/main/java/org/listenbrainz/android/model/dao/ArtistDao.kt
- app/src/main/java/org/listenbrainz/android/model/dao/SongDao.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/SongScreen.kt
- fastlane/metadata/android/en-US/changelogs/49.txt
- fastlane/metadata/android/en-US/changelogs/50.txt
As per [MOBILE-192](https://tickets.metabrainz.org/browse/MOBILE-192) the collections in the player were not sorted in any way. I have made the following changes to make this experience more usable and consistent:
- Added `ORDER BY` clauses to the DOAs for the problematic collections. This provides a sane default sorting by name/title.
- Removed the additional sorting from the `SongScreen` so that the list on the `BrainzPlayerScreen` and `SongScreen` are consistent, as with the other collection screens.
> MOBILE-192: Sort Collections by Name/Title by Default

- app/src/main/java/org/listenbrainz/android/ui/navigation/BottomNavigationBar.kt
This PR resolves an issue where the Profile tab in the Bottom Navigation Bar failed to update its selected state. The problem occurred due to route comparison logic that did not account for variations in routes such as `profile/{username}`.
Changes Made
- Updated the route comparison logic to handle both static and parameterized routes.
- Verified consistent behavior across all navigation items in the Bottom Navigation Bar.
Issue Link
Linked to issue [MOBILE-204](https://tickets.metabrainz.org/projects/MOBILE/issues/MOBILE-204).
> Mobile-204: Profile icon in the Bottom Navigation Bar does not update its selected state

- app/src/main/java/org/listenbrainz/android/ui/screens/profile/listens/ListensScreen.kt
This PR addresses the following UI issues in the profile screen [(Images):](https://imgur.com/a/images-0OkH5wA)  
1. **Background Width Issue (In light mode)**  
- Ensures the background of the followers section and similar users section spans the full width of the screen.  
2. **Padding Issue in Followers Section**  
- Adds proper padding to the right side of the follower cards to prevent them from touching the screen’s edge.  
3. **Empty Similar Users Section**  
- Hides the similar users section if no data is available.  
Let me know if any further changes are required!
> Fix: Minor ui bugs in Profile Screen

- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/util/BrainzPlayerExtensions.kt
The following changes have been made in this PR:
1. Fixed the song duration showing as 0:00 by passing duration in BrainzPlayerExtensions.kt
1. On the player screen, made a bunch of ui changes for consistency
* The row containing the song title and the heart icon now uses SpaceBetween (for proper spacing)
* Made the padding of song title row, progress bar and buttons row somewhat consistent
* The cards below "Listening now" are no longer bound to max 600.dp (this caused issues when the phone was rotated, see image below) and are now properly spaced.
Please let me know if any further changes are required.
Issue Screenshots:
Fixed player screen:
(cards fill the screen correctly)
---
Issue on Bug Tracker: [MOBILE-206](https://tickets.metabrainz.org/browse/MOBILE-206)
> Fixed Song Duration bug + Player Screen UI changes

- app/src/main/java/org/listenbrainz/android/model/artist/ArtistPayload.kt
- app/src/main/java/org/listenbrainz/android/model/artist/SimilarArtists.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ArtistViewModel.kt
This pull request addresses a bug caused due to improper mapping of Json response to kotlin objects which resulted in this error:
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 173912 path $.similarArtists`
Because of this bug, the artist data was not being displayed.
The error has been fixed by creating a `SimilarArtists` data class which contains list of artists.
The changes are as follows: 
Issue:
Fix:
> FIX: Artist page not displaying data

- app/src/main/java/org/listenbrainz/android/ui/components/BrainzPlayerListenCard.kt
- app/src/main/java/org/listenbrainz/android/ui/components/ListenCardSmall.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/AlbumsOverviewScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/ArtistsOverviewScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/OverviewScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/RecentPlaysOverviewScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/SongsOverviewScreen.kt
The following changes have been made in this PR:
1. Added the missing `error` argument in `AsyncImage` of both `ListenCardSmall` and `BrainzPlayerListenCard`, so that `errorAlbumArt` properly shows on the cards, instead of blank space.
2. Added a rectangular clip to both `ListenCardSmall` & `BrainzPlayerListenCard`, so that `R.drawable.ic_erroralbumart` appears on the cards with no rounded corners on the left side, in line with normal album/cover arts.
3. Added proper `errorAlbumArt` arguments to multiple brainzplayer overview screens (with suitable drawables as shown in images below)
4. Changed `errorIcon` argument for cards in `OverviewScreen.kt` to better match the intended category (`ic_song` for songs & `ic_album` for albums
Please let me know if any changes are required, especially …
> Fixed empty cover art showing blank space on brainzplayer & overview screens

- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
This pull request includes changes to the `BrainzPlayerBackDropScreen` in the ListenBrainz Android app to enhance the user interface and improve functionality. The most important changes include the addition of a back button handler and passing the `backdropScaffoldState` to the `PlayerScreen` function.
Enhancements to user interface and functionality:
* [`fun BrainzPlayerBackDropScreen(`](diffhunk://#diff-4feab51026955f2e97a718bc2b191c4e350da713aaadff15183eb966c290086fL147-R149): Modified to pass `backdropScaffoldState` to `PlayerScreen`.
* [`fun PlayerScreen(`](diffhunk://#diff-4feab51026955f2e97a718bc2b191c4e350da713aaadff15183eb966c290086fL168-R171): Added `backdropScaffoldState` parameter to manage the state of the backdrop.
* [`fun …
> Fix: Back Press in Player Screen Does Not Close the Player

- app/src/main/java/org/listenbrainz/android/ui/screens/profile/BaseProfileScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/listens/ListensScreen.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/UserViewModel.kt
This PR addresses issues where the **Follow button** state was not updating correctly across the ListenScreen and BaseProfileScreen also some ui bugs fixes. The following changes have been made:
- Corrected the styling of the **Follow Button** to match the light theme.
- Fixed text color inconsistencies in the **Compatibility** section for better visual consistency.
- Fixed **Follow Button** state management across ListenScreen and BaseProfileScreen.
https://github.com/user-attachments/assets/66407a61-a485-4833-a6c3-215b8bac6b77
https://github.com/user-attachments/assets/d1d79361-85cb-48c6-b496-641e08ab50e0
Let me know if there are any changes needed to the color scheme or any other adjustments!
> Fix: FollowButton state management and minor ui bugs

- app/build.gradle.kts
- app/src/main/java/org/listenbrainz/android/ui/components/SeekBar.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/OverviewScreen.kt
- app/src/main/java/org/listenbrainz/android/util/SongViewPager.kt
- gradle/libs.versions.toml
This pull request introduces the following changes to enhance the mini music player:
- **Persistent Mini Player:** The mini music player remains visible even when the song is paused.
- **Dynamic Background:** Background color now adapts to the poster using the Palette library.
- **Custom Seekbar:** Implemented a custom seekbar for better user experience.
- **Dependency Update:** Added the Palette library for dynamic color extraction.
**Screenshots-**
<p align="center">
</p>
**Issue Link:** [MOBILE-209](https://tickets.metabrainz.org/browse/MOBILE-209)
Let me know if any changes are required :)
> Feat: Handle mini music player like spotify

- app/src/main/java/org/listenbrainz/android/ui/screens/artist/ArtistScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/artist/ArtistUIState.kt
- app/src/main/java/org/listenbrainz/android/util/Utils.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ArtistViewModel.kt
1. Fixed lagging screen by using lazy row instead of row with vertical scroll, in `AlbumsCard` composable.
2. Reduced the size of cover art to 150.dp and gave a rounded  corner shape.
3. In Bio Card, added `Surface` to make rounded corner shape visible, changed some padding.
4. Created a separate composable `BioTag` for the tags, because same UI code was written twice for album tags and artist tags.
5. Make the `Row` of Link section scrollable to fix the Edit button issue.
6. Made other minor UI changes like padding and shape of review button.
7. Gave rounded corners to `AlbumsCard`.
Please let me know if any changes are required.
Before:
After: 
Issue: [Link](https://tickets.metabrainz.org/browse/MOBILE-208)
> MOBILE-208: Fix artist screen UI

- app/src/main/java/org/listenbrainz/android/ui/components/YimGraph.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/stats/StatsRange.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/stats/StatsScreen.kt
The following changes have been made in this PR:
1.  Changed the chart label color to be black irrespective of theme (was previously displayed as white on an off white background, leading to low contrast)
2. Fixed the color of "Listening Activity" and "Top..." text composables
3. Also added some padding between the axes and the chart background
4. Fixed a minor typo ("Tast Week" to "Last Week")
Please let me know if any further changes are required.
---
Issue on tracker board: [MOBILE-210](https://tickets.metabrainz.org/projects/MOBILE/issues/MOBILE-210?filter=allissues)
> MOBILE-210: Fixed stats chart label & heading colors not displaying correctly on Stats screen

- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
This PR resolves a bug where songs were not being deleted from the playlist in the BrainzPlayer screen. The following changes were made.
- Updated the logic in `BrainzPlayerBackDropScreen.kt` to properly remove the selected songs (checkedSongs) from the playlist.
- Ensured that the `currentPlayable`'s song list is mutable and modified correctly during the deletion process.
These updates ensure a smoother user experience when managing playlist in the BrainzPlayer feature.
**Before:**
https://github.com/user-attachments/assets/fe542c04-80c4-4e1d-a483-fa6fcb7af186
**Fixed:**
https://github.com/user-attachments/assets/bbb86c7d-c833-4b15-9f59-317ea720c893
Let me know if there are any changes needed!
> Fix: Delete song from BrainzPlayer playlist

- app/src/main/java/org/listenbrainz/android/ui/navigation/BottomNavigationBar.kt
- app/src/main/java/org/listenbrainz/android/ui/navigation/TopBar.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/main/MainActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/theme/Theme.kt
- app/src/main/java/org/listenbrainz/android/util/Utils.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
This pull request includes several changes to improve the appearance and functionality of the BrainzPlayer UI by introducing dynamic background colors and enhancing the TopBar component. The most important changes include adding dynamic background color functionality to the player screen, updating the TopBar to accept a customizable background color, and integrating the BrainzPlayerViewModel to manage these changes.
* Introduced dynamic background color and brush to the player screen and modified `AlbumArtViewPager` to use the dynamic background color. 
* Added a `backgroundColor` parameter to the `TopBar` component to allow customizable background colors.
* Added methods to the `BrainzPlayerViewModel` to compute and store the dominant color from the album art. This color is then used as …
> feat: Made the player screen background dynamic

- app/src/main/java/org/listenbrainz/android/ui/screens/album/AlbumScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/artist/ArtistScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/artist/ArtistUIState.kt
- app/src/main/java/org/listenbrainz/android/util/LinksUtil.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ArtistViewModel.kt
- app/src/main/res/drawable/settings_voice.xml
In this PR, I completed the TODO mentioned in the Artist Screen to move `linksMap` logic to `viewModel`.
`//TODO: Move this logic to vm and get map to ui state`
1. The mapping logic is used in both Artist and Album Screen, so I moved it to the `util` package.
2. Used `linksMap` in UiState to get the links.
3. `ImageVector.vectorResource` can be called only in compose function, so I have modifed `LinksCard` data class to contain resource id instead of ImageVector.
> Moved card Link logic to viewModel

- app/src/main/java/org/listenbrainz/android/service/BrainzPlayerEventListener.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/util/SongViewPager.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
This pull request includes updates to the `BrainzPlayer` feature in the ListenBrainz Android app.
* Added `onPositionDiscontinuity` method to update the current song index when a song auto transitions.
* Introduced `handleSongChangeFromPager` method to manage song changes from the pager.
* updated `skipToPreviousSong` to reset the song to the start.This was done since the song won't change if playing time exceeds a certain threshold.
* Replaced `mediaItem.collectAsState()` with `appPreferences.currentPlayable` for song list retrieval and added `LaunchedEffect` to handle song changes via list or buttons and pager.
* Added `Crossfade` animation for album art transitions in `AlbumArtViewPager`.
working video
https://github.com/user-attachments/assets/ca33b443-d800-4848-bef5-59ac5ed95d4d
> Feat: fixed the player screen and mini player pager

- app/src/main/java/org/listenbrainz/android/ui/navigation/BottomNavigationBar.kt
This pull request is about resolving the crash caused by java.lang.IllegalArgumentException related to navigation in the app.
Issue:
The crash occurred due to the NavController trying to navigate to a destination that did not exist in the navigation graph. Specifically, the app attempted to navigate to a destination with a URI of android-app://androidx.navigation/profile/, which was not defined in the navigation graph.
Changes Made:
Introduced a condition to handle cases where the username is null or blank.
If the username is null or blank, the app now passes "guest" as the username to the profile route.
**Before**
[Before.webm](https://github.com/user-attachments/assets/67c3ae0e-1b8c-4442-b8b9-eeedd0cc1f4a)
**After**
[After.webm](https://github.com/user-attachments/assets/d35002ef-4799-48 …
> Update Bottom NavigationBar with NullSafety

- app/src/main/java/org/listenbrainz/android/ui/screens/search/BrainzPlayerSearchScreen.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
This PR resolves the issue of UI state loss in BrainzPlayerSearchScreen during screen orientation changes. Previously, the search query and UI state were reset when the screen rotated. This issue has been fixed by introducing state retention in BrainzPlayerViewModel and ensuring that the UI state, including the search query and results, is preserved across orientation changes.
**Before**
https://github.com/user-attachments/assets/791c61e9-cf2b-4ae1-a9d0-42021e313007
**After**
https://github.com/user-attachments/assets/89b85ead-3c7d-4a90-96e4-1f12da8c6632
> Fixed UI State Loss In BrainzPlayerSearchScreen 

- app/src/main/java/org/listenbrainz/android/ui/screens/profile/listens/ListensScreen.kt
This PR resolves the issue of following and unfollowing a user. Previously, in the onFollowButtonClick function, the isFollowing status was passed . If the status was false, the followUser function would be called, even if the user was already following, leading to redundant actions. I have updated the logic so that if the user is not following, false will be passed to unfollow, and if the user is already following, true will be passed to unfollow the user.
**Before**
[Bug_Follow_Button_Before.webm](https://github.com/user-attachments/assets/7182a673-af2d-4066-aa6a-4f91f1cd5061)
**After**
[Bug_Follow_Button_After.webm](https://github.com/user-attachments/assets/5209758e-4782-4350-a177-126f7e3fe31d)
> Minor-UI-Logic-Bug

- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/SongsOverviewScreen.kt
This PR resolves the lag and freezing issues in SongsOverviewScreen by implementing Lazycolumn and coroutines, heavy operations are moved off the main thread, resulting in improved performance and reduced UI freezing and lag
**Before**
https://github.com/user-attachments/assets/bb258919-739d-465f-b225-8e31437bfba4
**After**
https://github.com/user-attachments/assets/9e6e9dc1-1d07-4acb-9259-053d01cbb592
> Fixed-Lag-In-SongsOverviewScreen

- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/AlbumsOverviewScreen.kt
This PR fixes a crash that happened when clicking on an album with no songs by adding proper null safety Checks a Toast is now shown if the album has 0 songs,also improves performance by  use of LazyColumn instead of Column
**Before**
https://github.com/user-attachments/assets/d5e55288-c53b-403e-ba37-d54a5968447a
**After**
https://github.com/user-attachments/assets/e69692ff-5bd5-40e4-bfc4-e81d9ebc9ab8
> Fixed crash and improve performance in AlbumsOverViewScreen

- app/src/main/java/org/listenbrainz/android/ui/components/BrainzPlayerDropDownMenu.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/ArtistsOverviewScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/RecentPlaysOverviewScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/overview/SongsOverviewScreen.kt
This PR fixes the Screen Reset Issue in the BrainzPlayerScreen by preserving the current tab position. Additionally  introduces a new feature to share songs in SongsOverviewScreen  via Android's native sharing options.
**Before**
https://github.com/user-attachments/assets/ede995f8-a57b-4a66-948f-79a3d16e6393
**After**
https://github.com/user-attachments/assets/e54b4373-42dc-453b-9baa-88541c7e0832
> Fixed Orientation Issue & Implemented Share Song Function

- app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
This PR fixes an issue where the app crashes when adding a song to the queue while no song is currently playing. The crash occurs because mediaID matching fails, causing indexOfFirst to return -1. Since -1 is an invalid index, this leads to an error.
The matching fails because initially, no song is playing. To fix this, I have set currentSongIndex to 0 when indexOfFirst returns -1, ensuring a valid index and preventing the crash. Now, songs can be added to the queue even if no song is currently playing
**Before**
https://github.com/user-attachments/assets/1a7e0d7d-cb34-430c-9c0e-9f40236366cd
**After**
https://github.com/user-attachments/assets/82feedc3-be9f-41d4-a90b-e92d4c617915
> Fixed crash for add queue option

- app/src/main/java/org/listenbrainz/android/model/AppNavigationItem.kt
- app/src/main/java/org/listenbrainz/android/model/playlist/AddCopyPlaylistResponse.kt
- app/src/main/java/org/listenbrainz/android/model/playlist/PlaylistExtensionData.kt
- app/src/main/java/org/listenbrainz/android/repository/playlists/PlaylistDataRepository.kt
- app/src/main/java/org/listenbrainz/android/repository/playlists/PlaylistDataRepositoryImpl.kt
- app/src/main/java/org/listenbrainz/android/service/PlaylistService.kt
- app/src/main/java/org/listenbrainz/android/ui/navigation/AppNavigation.kt
- app/src/main/java/org/listenbrainz/android/ui/navigation/TopBar.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/playlist/AddEditPlaylistScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/playlist/PlaylistDataUIState.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/BaseProfileScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/ProfileScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/playlists/PlaylistCardViews.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/playlists/UserPlaylistScreen.kt
- app/src/main/java/org/listenbrainz/android/util/CoverArtImageLinkExtractor.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/PlaylistDataViewModel.kt
- sharedTest/src/main/java/org/listenbrainz/sharedtest/mocks/MockPlaylistDataRepository.kt
In this PR,
1. Implemented Add and Edit playlist screen.
2. Created only one screen for both. If `null` is provided as `mbid` during navigation, it works like Create playlist screen, otherwise edit playlist screen.
3. Implemented search for `users` to add them as collaborators.
4. Added `PlaylistDataViewModel` which will be the common viewmodel for other playlist related screens.
5. Added FAB in `UserPlaylistScreen` to create playlist.
6. Used in-memory cache in viewmodel to store playlist data, so that the same playlist data need not fetched again and again.
- Planning next PR for PlaylistDetailScreen, then Add track to playlist.
- At last, I would work on enhancing performance of `UserPlaylistScreen`.
Please let me know if any changes are required.
> MOBILE-214: Create-Edit Playlist Screen implementation

- app/src/main/java/org/listenbrainz/android/ui/screens/artist/ArtistScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/playlist/PlaylistDetailScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/createdforyou/CreatedForYouScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/theme/Theme.kt
This PR aims to unify the gradient design across the app for a more consistent visual experience.
- Gradients in `ArtistScreen`, `CreatedForYouScreen`, and `PlaylistDetailScreen` have been updated to match the one used in `ListensScreen`.
---
A major issue in the Artist screen was related to the cover art implementation. Previously, it was rendered using a `WebView`, which caused a full reload every time the card left and re-entered the screen—resulting in a poor user experience.
To resolve this, I’ve replaced the `WebView` with the `CoverArtComposable` used in the `PlaylistDetailScreen`. However, the current layout of `CoverArtComposable` shows the cover art in a 3×3 grid, which slightly differs from the web version.
Here’s a reference image:
<br>
Let me know if you'd prefer a new …
> MOBILE-220: Gradient fix across all screens

- app/src/main/java/org/listenbrainz/android/ui/screens/profile/playlists/CollabPlaylistPagingSource.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/playlists/UserPlaylistPagingSource.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/playlists/UserPlaylistScreen.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/PlaylistDataViewModel.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/UserViewModel.kt
Fetching all playlist cover arts at once for users with multiple playlists leads to HitRateLimitExceeded error. 
To avoid this, I removed the previous async calls to fetch the cover art, and instead used Semaphores(2) allowing only two calls to fetch cover arts at the same time.
> FIX: Fetching cover Art in User Playlist screen
