metabrainz/listenbrainz-android

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/listenbrainz/android/presentation/features/artist/ArtistActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/musicsource/SongsData.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/dashboard/DashboardActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/dashboard/DashboardBackdropBackLayerContent.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/listens/ListensActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/release_list/ReleaseListAdapter.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/yim/YearInMusicActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/yim/YimViewModel.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/yim/navigation/YimNavigation.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/yim/screens/YimChartsScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/yim/screens/YimHomeScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/yim/screens/YimTopAlbumsScreen.kt
- app/src/main/java/org/listenbrainz/android/util/connectivityobserver/NetworkConnectivityObserver.kt
- Permissions were causing an issue, hence fixed it.
- Major code cleanup done.
> Rework permissions and Cleanup Code

- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/services/BrainzPlayerService.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/components/BottomNavigationBar.kt
- Animation while dragging Player Screen fixed
- <video src="https://user-images.githubusercontent.com/75999921/211207247-db98f92c-baad-4f44-8e49-c253a25e6e4b.mp4" controls="controls" style="max-width: 730px;">
</video>
> animation fixes

- app/src/main/java/org/listenbrainz/android/data/sources/brainzplayer/Playable.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/services/BrainzPlayerService.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerViewModel.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/album/AlbumScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/artist/ArtistScreen.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/components/Buttons.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/songs/SongScreen.kt
- app/src/main/java/org/listenbrainz/android/util/LBSharedPreferences.kt
- playables can be changed, now we can play an album, and songs of only that album will be played unless we change the playable.
https://user-images.githubusercontent.com/75999921/211518641-54064e49-fb8e-4a0c-a628-e4e201562bcc.mp4
> Playables are changeable now

- .github/dependabot.yml
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Updated to gradle 7.4
- Dependabot config added
> Bumped dependencies and added dependabot.yml

- .github/workflows/android-lint.yml
- .github/workflows/releaseBeta.yml
- .github/workflows/releaseProd.yml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- We need a crash logging framework for the app. This addition will help us identify the crashes which users face when using the app in production.
- Fixed our github workflows.
> Sentry Android SDK Addition

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/data/dao/SongDao.kt
- build.gradle
> Fatal crash fix (MOBILE-106)

- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/services/BrainzPlayerService.kt
- build.gradle
Changes made according to the docs.
> Fixed first startup crash

- app/src/debug/res/values/strings.xml
- The prod and debug apps currently looked identical to each other. This update will help distinguish them.
> Separate out the Prod and Debug Apps

- app/src/main/java/org/listenbrainz/android/presentation/UserPreferences.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/dashboard/DashboardActivity.kt
- app/src/main/java/org/listenbrainz/android/util/uicomponents/LBDialog.kt
Dialog appearance fixed for all cases.
> MOBILE-96 improvement

- app/src/main/java/org/listenbrainz/android/presentation/features/dashboard/DashboardActivity.kt
- https://tickets.metabrainz.org/browse/MOBILE-115
- The permission.values collection is being reduced. But the reduce method can only be applied to a non empty collection.
- This returns true if any element in the collection match the given predicate.
> Fixes MOBILE-115

- app/src/main/java/org/listenbrainz/android/data/sources/api/HeaderInterceptor.kt
- app/src/main/java/org/listenbrainz/android/data/sources/api/ListenBrainzServiceGenerator.kt
- app/src/main/java/org/listenbrainz/android/util/LBSharedPreferences.kt
- https://tickets.metabrainz.org/browse/MOBILE-116
- Add required checks to the code and cleanup done
> Code cleanup and fix MOBILE-116

- app/src/main/java/org/listenbrainz/android/data/sources/api/entities/listens/TrackMetadata.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/components/ListenCard.kt
https://tickets.metabrainz.org/browse/MOBILE-113
Made release_name nullable.
> Mobile-113

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/App.kt
- app/src/main/java/org/listenbrainz/android/presentation/Configuration.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/about/AboutActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/adapters/BlogAdapter.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/base/ListenBrainzActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/dashboard/DonateActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/login/LoginActivity.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/newsbrainz/NewsBrainzActivity.kt
- app/src/main/java/org/listenbrainz/android/util/BrainzPlayerExtensions.kt
- app/src/main/java/org/listenbrainz/android/util/ComparisonResult.kt
- build.gradle
- Updated sentry and room.
- General code cleanup done.
> Bump dependencies and Code Cleanup

- app/src/main/java/org/listenbrainz/android/data/sources/Constants.kt
- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/util/cacheService.kt
Created the cacheService and migrated recently played to work from their. it is generic class which can store value according to key in cache and on fetch it will give the list of object as user want and parse value in datatype which take value of data class.
@akshaaatt Please review it and specify the changes or any different type of approach you want.
> Feat: CacheService Created

- app/src/main/java/org/listenbrainz/android/presentation/features/brainzplayer/ui/playlist/PlaylistScreen.kt
https://tickets.metabrainz.org/browse/MOBILE-120
Added condition when hitting play. Showed a toast to notify the user that selected playlist is empty.
> MOBILE-120 BP crashes when playing an empty playlist.

- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/theme/Theme.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
**BrainzPlayer Changes**
- Added music duration text below the seek bar to convey more information to the user
- Fixed button colors to be visible in both dark and light themes.
**Changes can be seen below**
> UI Fixes : Added music duration text & fixed player control colors 

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/application/App.kt
- app/src/main/java/org/listenbrainz/android/repository/AppPreferencesImpl.kt
- app/src/main/java/org/listenbrainz/android/service/ListenService.kt
- app/src/main/java/org/listenbrainz/android/service/ListenSubmitService.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/settings/SettingsActivity.kt
- app/src/main/java/org/listenbrainz/android/util/Constants.kt
- app/src/main/java/org/listenbrainz/android/util/ListenBrainzServiceGenerator.kt
- app/src/main/java/org/listenbrainz/android/util/ListenHandler.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSessionListener.kt
- We had messed up the api call. Fixed that.
- General code cleanup done.
> Fix Listens Service

- .github/workflows/android-lint.yml
- .github/workflows/android.yml
- .github/workflows/releaseBeta.yml
- .github/workflows/releaseProd.yml
- app/build.gradle
- app/src/main/java/org/listenbrainz/android/application/App.kt
- app/src/main/java/org/listenbrainz/android/ui/components/ListenBrainzActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/AllUsersListens.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListensScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/login/LoginActivity.kt
- app/src/main/java/org/listenbrainz/android/util/Configuration.kt
- app/src/main/java/org/listenbrainz/android/util/Constants.kt
- app/src/main/java/org/listenbrainz/android/util/Log.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ListensViewModel.kt
- Play the llistens via the Amazon Music app (addition added and commented)
- Spotify code refactored
> Minor Code Refactoring

- .github/dependabot.yml
To reduce the amount of spam in #metabrainz IRC channel.
> dependabot: Reduce max open PRs

- app/src/androidTest/java/org/listenbrainz/android/LoginActivityTest.kt
- app/src/androidTest/java/org/listenbrainz/android/YearInMusicActivityTest.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/brainzplayer/BrainzPlayerBackDropScreen.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
The Previous pr got some issue so I am closing it, This is the same Pr with Same functionality 
@akshaaatt Plz suggest any change if required
> Feat:User Able to remove the Song from the Queue

- app/src/main/java/org/listenbrainz/android/ui/components/YimNavigationStation.kt
- For now, we have intents which open up the Threejs widgets
> Add 3D widgets to the app

- app/build.gradle
- app/src/androidTest/java/org/listenbrainz/android/LoginActivityTest.kt
- app/src/androidTest/java/org/listenbrainz/android/YearInMusicActivityTest.kt
- app/src/androidTest/java/org/listenbrainz/android/data/dao/DaoTest.kt
- app/src/main/java/org/listenbrainz/android/di/LoginRepositoryModule.kt
- app/src/main/java/org/listenbrainz/android/repository/AppPreferencesImpl.kt
- app/src/main/java/org/listenbrainz/android/repository/LoginRepository.kt
- app/src/main/java/org/listenbrainz/android/repository/LoginRepositoryImpl.kt
- app/src/main/java/org/listenbrainz/android/ui/components/ListenBrainzActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/navigation/AppNavigation.kt
- app/src/main/java/org/listenbrainz/android/ui/navigation/BottomNavigationBar.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/login/LoginActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/login/LoginScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/login/ProfileScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim/YearInMusicActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/theme/Theme.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/LoginViewModel.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ProfileViewModel.kt
- app/src/main/res/values/strings.xml
- sharedTest/build.gradle
-  YimActivityTest
-  Dao Tests
-  LoginActivityTests
> Converted Login activity to composable and fixed all tests.

- app/src/main/java/org/listenbrainz/android/ui/screens/settings/SettingsActivity.kt
https://user-images.githubusercontent.com/87614560/228992955-91722ea8-d8e8-455e-8ebe-5e087ed63eed.mp4
@akshaaatt please review
> Theme fixed

- app/src/main/java/org/listenbrainz/android/ui/components/LBLoadingAnimation.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/AllUsersListens.kt
Experimental animation but quite stable with very less recompositions.
> LB loading animation added

- app/src/main/java/org/listenbrainz/android/ui/screens/login/ProfileScreen.kt
[Mobile-135](https://tickets.metabrainz.org/browse/MOBILE-135)
> MOBILE-135: Fixed login button inaccessible

- app/src/main/java/org/listenbrainz/android/di/ListensRepositoryModule.kt
- app/src/main/java/org/listenbrainz/android/model/AdditionalInfo.kt
- app/src/main/java/org/listenbrainz/android/model/ListenSubmitBody.kt
- app/src/main/java/org/listenbrainz/android/repository/ListensRepository.kt
- app/src/main/java/org/listenbrainz/android/repository/ListensRepositoryImpl.kt
- app/src/main/java/org/listenbrainz/android/service/ListenScrobbleService.kt
- app/src/main/java/org/listenbrainz/android/util/ListenHandler.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSessionListener.kt
https://tickets.metabrainz.org/browse/MOBILE-134
> MOBILE-134: Fixed ListenSubmitBody and added more metadata.

- .github/workflows/releaseBeta.yml
- .github/workflows/releaseProd.yml
- app/build.gradle
- The gradle file was not config'ed properly
- Added ui tests to deployment pipelines
> Fix Instrumentation tests

- app/src/main/java/org/listenbrainz/android/application/App.kt
- app/src/main/java/org/listenbrainz/android/repository/AppPreferences.kt
- app/src/main/java/org/listenbrainz/android/repository/AppPreferencesImpl.kt
- app/src/main/java/org/listenbrainz/android/repository/ListensRepository.kt
- app/src/main/java/org/listenbrainz/android/repository/ListensRepositoryImpl.kt
- app/src/main/java/org/listenbrainz/android/service/ListensService.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListeningAppsList.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListensScreen.kt
- app/src/main/java/org/listenbrainz/android/util/Constants.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ListensViewModel.kt
- app/src/test/java/org/listenbrainz/android/LinkedServiceUtilTest.kt
- sharedTest/src/main/java/org/listenbrainz/sharedtest/mocks/MockAppPreferences.kt
Removed automatic addition of spotify into listening blacklist and added a small warning if spotify account is linked to LB.
> Fix: Remove automatic disabling of Spotify

- app/src/androidTest/java/org/listenbrainz/android/di/TestAppModule.kt
- app/src/main/java/org/listenbrainz/android/di/AppModule.kt
- app/src/main/java/org/listenbrainz/android/repository/preferences/AppPreferences.kt
- app/src/main/java/org/listenbrainz/android/repository/preferences/AppPreferencesImpl.kt
- app/src/main/java/org/listenbrainz/android/service/BrainzPlayerServiceConnection.kt
- app/src/main/java/org/listenbrainz/android/util/Constants.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSessionListener.kt
- app/src/main/java/org/listenbrainz/android/util/Utils.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/BrainzPlayerViewModel.kt
- sharedTest/src/main/java/org/listenbrainz/sharedtest/mocks/MockAppPreferences.kt
- Devices without notification access can now submit listens to ListenBrainz by locally playing the song from the app.
> Android Go Scrobbler

- app/src/main/java/org/listenbrainz/android/di/brainzplayer/DaoModule.kt
- app/src/main/java/org/listenbrainz/android/di/brainzplayer/DatabaseModule.kt
- app/src/main/java/org/listenbrainz/android/di/brainzplayer/ListensDatabase.kt
- app/src/main/java/org/listenbrainz/android/di/brainzplayer/ListensScrobbleDatabase.kt
- app/src/main/java/org/listenbrainz/android/model/Listen.kt
- app/src/main/java/org/listenbrainz/android/model/ListenSubmitBody.kt
- app/src/main/java/org/listenbrainz/android/model/ListenTrackMetadata.kt
- app/src/main/java/org/listenbrainz/android/model/dao/PendingListensDao.kt
- app/src/main/java/org/listenbrainz/android/repository/listens/ListensRepositoryImpl.kt
- app/src/main/java/org/listenbrainz/android/repository/socket/SocketRepositoryImpl.kt
- app/src/main/java/org/listenbrainz/android/service/ListenScrobbleService.kt
- app/src/main/java/org/listenbrainz/android/service/ListenSubmissionWorker.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSessionListener.kt
- app/src/main/java/org/listenbrainz/android/util/ListenSubmissionState.kt
- app/src/main/java/org/listenbrainz/android/util/TypeConverter.kt
- app/src/main/java/org/listenbrainz/android/util/Utils.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ListensViewModel.kt
Cleanup and added "listen" to socket listeners so that listen's list is updated automatically.
**Update:** Listens that are not submitted are now saved and bulk submitted at next available chance, i.e., when internet connection comes back or conditions are met.
> Cleanup and subscribed to listen's list

- app/src/main/java/org/listenbrainz/android/di/RemotePlayerRepositoryModule.kt
- app/src/main/java/org/listenbrainz/android/repository/remoteplayer/RemotePlaybackHandler.kt
- app/src/main/java/org/listenbrainz/android/repository/remoteplayer/RemotePlaybackHandlerImpl.kt
- app/src/main/java/org/listenbrainz/android/repository/remoteplayer/RemotePlayerRepository.kt
- app/src/main/java/org/listenbrainz/android/repository/remoteplayer/RemotePlayerRepositoryImpl.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/dashboard/DashboardActivity.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/feed/FeedScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListeningNowCard.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListeningNowOnSpotify.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListensScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ProgressBar.kt
- app/src/main/java/org/listenbrainz/android/ui/theme/Theme.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/FeedViewModel.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/ListensViewModel.kt
Final refactor of remote players.
> MOBILE-140: Feed section phase 2.3 Part 2

- app/src/main/java/org/listenbrainz/android/ui/components/Switch.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/listens/ListeningAppsList.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/settings/SettingsScreen.kt
- UI fixes
- Alignment updates
> Update Settings Screen

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/ui/screens/onboarding/FeaturesActivity.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/DashBoardViewModel.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/FeaturesViewModel.kt
- app/src/main/res/values/strings.xml
- Allow the user to sign in from onboarding
- Make the user allow for permission from onboarding
> Improve First time experience and fix tests

- app/src/main/java/org/listenbrainz/android/util/Utils.kt
- Logger shouldn't be used in utils directly.
> Fix tests - Logger

- app/src/main/java/org/listenbrainz/android/model/yimdata/YimShareable.kt
- app/src/main/java/org/listenbrainz/android/ui/components/Yim23ShareButton.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23BaseScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23LandingScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23LastScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23StatsScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/navigation/Yim23Navigation.kt
- app/src/main/java/org/listenbrainz/android/ui/theme/Yim23Theme.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/Yim23ViewModel.kt
> Add status bar and nav bar colors

- app/src/main/java/org/listenbrainz/android/model/yimdata/Yim23Data.kt
- app/src/main/java/org/listenbrainz/android/model/yimdata/Yim23TopDiscoveries.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23DiscoveriesListScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23DiscoveriesScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23LastScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23MissedSongsListScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23MissedSongsScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23MusicBuddiesScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23NewAlbumsFromTopArtistsScreen.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/Yim23ViewModel.kt
YIM on android was crashing after the playlists screen
I realized that the api structure has changed after hitting it once. So, I have changed the YimData structure a bit (basically their serialized json names) and have also added nullorempty checks for good measure.
Could someone please test locally and confirm
Please check IRC, have posted there
> FIxed YIM CRASH after Playlist

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/model/yimdata/Yim23Data.kt
- app/src/main/java/org/listenbrainz/android/model/yimdata/Yim23TopDiscoveries.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23DiscoveriesListScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23DiscoveriesScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23LastScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23MissedSongsListScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23MissedSongsScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23MusicBuddiesScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23NewAlbumsFromTopArtistsScreen.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/Yim23ViewModel.kt
> Dev to Main

- app/build.gradle
- app/src/main/java/org/listenbrainz/android/ui/screens/feed/FeedScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/yim23/Yim23LandingScreen.kt
- build.gradle
- Bumped dependencies
- YIM23 back button was not killing the yim activity and continuing things there which removed the top and bottom bars
> Fix yim back button and bump

- app/src/main/java/org/listenbrainz/android/ui/screens/profile/ListenBrainzWebClient.kt
- Many users have reported for failed login. We fix this by improving the webview implementation
> Login issue fix

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/listenbrainz/android/viewmodel/DashBoardViewModel.kt
1) Removed unused permissions.
2) Remove `android:usesClearTextTraffic` as it isn't used anywhere. 
3) DependencyInfo changes.
> F-droid fixes

- app/src/main/java/org/listenbrainz/android/model/Listen.kt
- app/src/main/java/org/listenbrainz/android/model/SocialUiState.kt
- app/src/main/java/org/listenbrainz/android/model/feed/FeedListenArtist.kt
- app/src/main/java/org/listenbrainz/android/model/user/Recording.kt
- app/src/main/java/org/listenbrainz/android/ui/components/ListenCardSmall.kt
- app/src/main/java/org/listenbrainz/android/ui/components/dialogs/DialogsState.kt
- app/src/main/java/org/listenbrainz/android/ui/components/dialogs/PersonalRecommendationDialog.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/feed/FeedScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/feed/SocialDropdown.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/BaseProfileScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/listens/ListensScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/profile/stats/StatsScreen.kt
- app/src/main/java/org/listenbrainz/android/viewmodel/SocialViewModel.kt
1. Created extension function to convert a `Listen` to `Metadata` which is used to send data to dropdowns.
2. Dropdowns were very difficult to support. Created a drop in replacement which supports previews and automatically handles all dropdown logic.
These changes are currently used in `ListensScreen` and are tested to work as expected.
> DX Changes

- app/src/main/java/org/listenbrainz/android/ui/screens/settings/SettingsCallbacks.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/settings/SettingsOption.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/settings/SettingsScreen.kt
- app/src/main/java/org/listenbrainz/android/ui/theme/Theme.kt
- app/src/main/java/org/listenbrainz/android/util/Timer.kt
1. Delete account button.
2. Logout dialog.
3. Used components for settings options to reuse code.
4. Previews are now available for settings screen.
> Settings Revamp

- app/src/main/java/org/listenbrainz/android/ui/screens/search/SearchScreen.kt
> Search Screen: Minor UX fix

- app/src/main/java/org/listenbrainz/android/model/feed/FeedEventType.kt
- app/src/main/java/org/listenbrainz/android/ui/screens/feed/FeedScreen.kt
This pr is for the issue in feed  screen where  when a user taps on the "You" in the feed, the app navigates to the profile screen. However, the profile screen shows null values,
Before
https://github.com/user-attachments/assets/d4d86e84-52d1-4a58-b184-52665bc5aa3f
After
https://github.com/user-attachments/assets/2ddb6a4d-c15b-401b-8c24-62f9219afa36
> Fix null profile screen if we click on "You" in feed
